#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'git'
cookbook 'build-essential'
cookbook 'chef-client'

cookbook 'rbenv'

cookbook "nginx"
cookbook "postfix"
cookbook "sudo"
cookbook "rbenv"
cookbook "ruby_build"

cookbook "mongodb"

# cookbook "rails", path: "vendor/cookbooks/rails"

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
